### ISSUE TITLE
Member table delete duplication

### ISSUE THREAD

**Issue by bhdd** [strangerstudios/pmpro-toolkit#1]
The script is trying to truncate the $wpdb->pmpro_memberships_users table twice.

Line 10 of adminpages/scripts.php appears to be an effective dupe of line 7 (first and last lines of the array below), which the clean_member_tables option uses to truncate the tables.

```
    $pmprodev_member_tables = array(
        $wpdb->pmpro_memberships_users,
        $wpdb->pmpro_membership_orders,
        $wpdb->pmpro_discount_codes_uses,
        $wpdb->pmpro_memberships_users
    );
```

**Comment by ideadude** [comment]
Fixed here:
https://github.com/strangerstudios/pmpro-toolkit/commit/a8e9a96a9a613ced3625528aebd6aab804e2d62c

Thanks!
