### ISSUE TITLE
Not all usermeta being deleted

### ISSUE THREAD

**Issue by bhdd** [strangerstudios/pmpro-toolkit#2]
When deleting all non-Administrator WP users, only the first entry in the $wpdb->usermeta for each user is removed, leaving a lot of orphaned rows behind.

It appears to be due to the "LIMIT 1" in the SQL on line 132 of adminpages/scripts.php.
`$wpdb->query("DELETE FROM $wpdb->usermeta WHERE user_id = " . $user_id . " LIMIT 1");`

**Comment by ideadude** [comment]
Fixed here:
https://github.com/strangerstudios/pmpro-toolkit/commit/05d15b7575e3335e7a5e96f5784bcb7f4a17d9a0

Thanks!
