### ISSUE TITLE
Feature Request: option to Delete all member data by user ID(s)

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-toolkit#27]
If a site owner needs to remove all membership data for a specific user.
Currently, you can delete ALL data.
`Delete all member data. (wp_pmpro_memberships_users, wp_pmpro_membership_orders, wp_pmpro_discount_codes_uses)`

Would be nice to do this one user at a time.
An option to remove this information just for 1 user id.

**Comment by mircobabini** [comment]
We already have this feature. I mean, we extend the standard WordPress feature to erase user data.

Tools > Erase Personal Data (url: /wp-admin/erase-personal-data.php)

**Comment by kimcoleman** [comment]
Yes let's rather recommend that people use the Request to be Forgotten systems in core WP.
