### ISSUE TITLE
Bug: cannot access category content when Developer’s Toolkit active

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-toolkit#28]
**Describe the bug**
When Developer’s Toolkit is activated, category content cannot be accessed.

**To Reproduce**
1. Go to category
2. Click on a post 
3. Cannot access content when logged in

**Screenshots**
Logged in
![image](https://user-images.githubusercontent.com/4752949/183979135-daffc749-586b-4231-8b9f-561037bc9d56.png)
Logged out
![image](https://user-images.githubusercontent.com/4752949/183979426-cf21003b-4e98-4e4e-9f95-af18106125e3.png)

**Expected behavior**
You should be able to see category content without being logged in when the Developer’s Toolkit is activated.

This was reported in ticket 438543.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.9.1, Developer’s Toolkit Add On 0.7, Twenty Twenty-One theme 1.6, WordPress 6.0.1, PHP 7.4.1
```
</details>

**Comment by kimcoleman** [comment]
I cannot recreate this in the current version of PMPro with the same settings as above. We did updates to our content filters so this is most likely resolved. Closing until we get new reports of this issue.
