### ISSUE TITLE
Feature Request: Export and Import User Fields

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-toolkit#29]
**Is your feature request related to a problem? Please describe.**
When working with multiple PMPro installations some custom User Fields groups and fields created per site are the same and have to be manually created on each site.

**Describe the solution you'd like**
The ability to export the JSON for these User Fields created in the GUI and import them into another site, eliminating the step to manually creating these fields.

**Describe alternatives you've considered**
Export and Import the JSON stored for this option from the database.

**Additional context**
None.

**Comment by ipokkel** [comment]
This feature was also requested in ticket #523576

**Comment by kimcoleman** [comment]
Looks like this is addressed here: https://github.com/strangerstudios/pmpro-toolkit/pull/30

**Comment by dparker1005** [comment]
Will be released in 1.0
