### ISSUE TITLE
Clicking in textarea toggles attached checkbox

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/pmpro-toolkit#8]
Can reproduce on Safari, but not Chrome

May be due to how Safari handles clicking on <label/> tags attached to an <input/>.

demo: https://files.slack.com/files-pri/T042RQSG0-FH40MBG1H/download/pmpro-toolkit-form-checkbox.mov

**Comment by ideadude** [comment]
Nice catch. Odd. I removed the labels around the scripts that had input fields/etc. https://github.com/strangerstudios/pmpro-toolkit/commit/f2c8bb46a357bd4cb2087460dfd379098c334663
